# Generated by Django 5.1.4 on 2025-09-26 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('lector', 'Lector'), ('redactor', 'Redactor'), ('editor', 'Editor'), ('admin', 'Administrador')], default='lector', max_length=20),
        ),
        migrations.CreateModel(
            name='ColaboracionNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_publicar', models.BooleanField(default=False)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboraciones', to='noticias.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'noticia')},
            },
        ),
    ]
